services :
   - type : web
     name : gofilterbot
     runtime : go
     repo : https://github.com/Jisin0/Go-Filter-Bot.git
     buildCommand: go build .
     startCommand: ./Go-Filter-Bot
     envVars :
       - key: MONGODB_URI
         value : mongodb+srv://xblade1980:<db_password>@cluster0.jqcpu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
       - key: ADMINS
         value: 6354431214
       - key: BOT_TOKEN
         value : 7203340734:AAFx-u-EYh2vd81rBoVJ59u6TmvjDXnI2z4
